
#1
# FROM almalinux:9
# RUN mkdir /tmp/docker
# RUN cd /tmp/docker
# RUN pwd
# RUN echo "Hello world" > hello.txt
# CMD ["sleep", "100"]

#2
FROM almalinux:9
RUN mkdir /tmp/docker
WORKDIR /tmp/docker
RUN pwd
RUN echo "Hello world" > hello.txt
CMD ["sleep", "100"]